<a href="https://colab.research.google.com/github/Elwing-Chou/tibame_20260714/blob/main/tibame20260822.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import json
import pandas as pd
import urllib.request as req
import os

def save_danmu_to_csv(sn, description=None):
    if description == None:
        dirname = "baha"
    else:
        dirname = f"baha/{description}"
    if not os.path.exists(dirname):
        os.makedirs(dirname)

    # url = "https://api.gamer.com.tw/anime/v1/danmu.php?videoSn={}&geo=TW%2CHK".format(sn)
    url = f"https://api.gamer.com.tw/anime/v1/danmu.php?videoSn={sn}&geo=TW%2CHK"
    f = req.urlopen(url)
    content = f.read()
    content = json.loads(content)

    danmus = content["data"]["danmu"]

    df = pd.DataFrame(danmus)
    df.to_csv(f"{dirname}/{sn}.csv",
              encoding="utf-8",
              index=False)
    return df

save_danmu_to_csv("26850", "鬼滅")

                   text    color  size  position   time        sn      userid
0              看完2刷2/15  #FFFFFF     1         0      0  25410397  amanda4a03
1                 好帥\n簽  #FFFFFF     1         2      0  25652598   s52241110
2                  油鍋篇！  #0036FA     2         2      0  29426133    Lucian01
3                     我  #FDE53D     1         0      0  33663511  kh69xvvspn
4     看封面就知道本片不適合老少咸宜觀看  #FF9625     2         2      6  45407686    d7261904
...                 ...      ...   ...       ...    ...       ...         ...
2996          善意什麼時候解開的  #FFFFFF     1         0  28053  28932406  safiya0820
2997     樓下白字說得對，沒有一個正常  #FFFFFF     1         0  28065  49967935    abcd7849
2998                 油鍋  #FFFFFF     1         0  28110  25430419   b30838695
2999               嗨\n嗨  #A7FE39     1         0  28119  27845675     coco447
3000        2025.7.27 *  #FFFFFF     1         0  28119  45877991     s935602

[3001 rows x 7 columns]

- 2: 成功
- 3: 轉址
- 4: Error
    - 404: Not Found
    - 403: Forbidden
        - 至少要先成功幾次: IP ban
        - 第一次就失敗

- 送出: 網址+headers
- 回應: 回應+headers

- 無數個長方形(區塊)所構成



```python
<a href="網址"> 開始
    顯示內容
</a> 結束

1. 名稱: 決定是什麼
a-> 超連結 img-> 圖片 video->影片

2. 屬性: 決定細節
a href="網址" img/video src="網址"

3. 顯示內容
```

In [13]:
import urllib.request as req
# BeautifulSoup: 幫你分析html
import bs4 as bs

# 之所以還是403, 是因為巴哈鎖海外ip, 所以你在colab上執行是會被拒絕的
# url = "https://ani.gamer.com.tw/animeVideo.php?sn=26850"
url = "https://github.com/Elwing-Chou/tibame_20260714/raw/refs/heads/main/baha.html"
h = {
    "User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36 Edg/151.0.0.0"
}
r = req.Request(url, headers=h)
f = req.urlopen(r)
content = f.read()
# 型態轉換: 上次 json.loads
html = bs.BeautifulSoup(content)
# 專屬功能: find find_all (html名字, 篩選條件)
for link in html.find_all("a"):
    # 內容: .get_text()
    # 特殊屬性: ["href"]
    link_href = link["href"]
    if link_href.startswith("?sn"):
        print("下載彈幕:", link_href)
        sn = link_href.split("=")[-1]
        save_danmu_to_csv(sn, description="鬼滅")

下載彈幕: ?sn=26850
下載彈幕: ?sn=27165
下載彈幕: ?sn=27166
下載彈幕: ?sn=27167
下載彈幕: ?sn=27339
下載彈幕: ?sn=27340
下載彈幕: ?sn=27592
下載彈幕: ?sn=27593
下載彈幕: ?sn=27867
下載彈幕: ?sn=27868
下載彈幕: ?sn=27869
下載彈幕: ?sn=30991
下載彈幕: ?sn=30992
下載彈幕: ?sn=30993
下載彈幕: ?sn=30994
下載彈幕: ?sn=30995
下載彈幕: ?sn=30996
下載彈幕: ?sn=30997
下載彈幕: ?sn=30998
下載彈幕: ?sn=30999
下載彈幕: ?sn=31000
下載彈幕: ?sn=31001

In [18]:
import os
import glob
import pandas as pd

total = []
for fp in glob.glob("baha/*/*.csv"):
    df = pd.read_csv(fp, encoding="utf-8")
    sn = os.path.basename(fp).replace(".csv", "")
    # dataframe增加新行
    df["sn"] = sn
    total.append(df)

total_df = pd.concat(total)
# 如果你想reset列標籤: total_df = total_df.reset_index()
total_df

,index,text,color,size,position,time,sn,userid
0,0,簽,#A7FE39,1,0,0,30992,k9219059
1,1,2022.8.22第一個 耶～～😋,#FF02D3,2,0,9,30992,Amy20080403
2,2,花街=遊郭=遊戲人間場所,#FFFFFF,1,0,35,30992,eggplant171
3,3,善逸為什麼那麼懂w瑟瑟齁,#FFFFFF,1,0,151,30992,huooyy
4,4,2025/5/29,#FFFFFF,1,0,186,30992,GAJSBDJS
...,...,...,...,...,...,...,...,...
35995,288,兩個大胸鬼,#FFFFFF,1,0,12939,30996,aaidjd
35996,289,龍顯蕙聲線真的很適合妖媚的鬼,#FFFFFF,1,0,13130,30996,eggplant171
35997,290,玟次郎？,#FDE53D,2,2,13855,30996,lpx1007
35998,291,戳爆他的泡泡！,#FFFFFF,1,0,13938,30996,LWT1109
35999,292,別把他弄醒了，睡著時比較可靠呀,#FFFFFF,1,0,13958,30996,gamefan

- pandas兩大操作
    - 過濾: 過濾你想要的 row
    - 轉換: 轉換你需要轉換的 col

In [21]:
# 過濾: 準備跟你資料筆數一樣多的True/False
fil = [True, False, True]
total_df.head(3)[fil]

   index          text    color  size  position  time     sn       userid
0      0             簽  #A7FE39     1         0     0  30992     k9219059
2      2  花街=遊郭=遊戲人間場所  #FFFFFF     1         0    35  30992  eggplant171